# command line: main.py --config ./config/team/enhance/degcn_J.yaml

base_lr: 0.1
batch_size: 64
config: ./config/team/enhance/degcn_J.yaml
cosine_epoch: 60
device:
- 0
eval_interval: 5
feeder: feeders.feeder_uav_human_3d.FeederUAVHuman
half: true
ignore_weights: []
log_interval: 100
model: model.degcn.Model
model_args:
  eta: 4
  graph: graph.uav.Graph
  graph_args:
    labeling_mode: spatial
  k: 8
  num_class: 155
  num_person: 2
  num_point: 17
  num_stream: 2
model_saved_name: ''
nesterov: true
num_epoch: 80
num_worker: 0
optimizer: SGD
phase: train
print_log: true
save_epoch: 0
save_interval: 1
save_score: true
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 35
- 60
- 75
test_batch_size: 64
test_feeder_args:
  bone: false
  data_path: ../data/uav-human/3d/val_joint_C.npy
  debug: false
  label_path: ../data/uav-human/3d/val_label_C.npy
  p_interval:
  - 0.95
  split: test
  vel: false
  window_size: 64
train_feeder_args:
  bone: false
  data_path: ../data/uav-human/3d/train_joint_C.npy
  debug: false
  label_path: ../data/uav-human/3d/train_label_C.npy
  normalization: false
  p_interval:
  - 0.5
  - 1
  random_choose: false
  random_move: false
  random_rot: true
  random_shift: false
  split: train
  vel: false
  window_size: 64
warm_up_epoch: 5
weight_decay: 0.0004
weights: null
work_dir: ./work_dir/enhance/degcn_J
