# command line: main.py --config ./config/team/test/D_B.yaml --phase test --save-score True --weights ./checkpoints/epoch_70_17920.pt --device 0

base_lr: 0.1
batch_size: 64
config: ./config/team/test/D_B.yaml
cosine_epoch: 60
device:
- 0
eval_interval: 5
feeder: feeders.feeder_uav_human_3d.FeederUAVHuman
half: true
ignore_weights: []
log_interval: 100
model: model.degcn.Model
model_args:
  eta: 4
  graph: graph.uav.Graph
  graph_args:
    labeling_mode: spatial
  k: 8
  num_class: 155
  num_person: 2
  num_point: 17
  num_stream: 2
model_saved_name: ''
nesterov: true
num_epoch: 80
num_worker: 0
optimizer: SGD
phase: test
print_log: true
save_epoch: 0
save_interval: 1
save_score: true
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 35
- 60
- 75
test_batch_size: 64
test_feeder_args:
  bone: true
  data_path: ./data/uav-human/test_joint_B.npy
  debug: false
  label_path: ./data/uav-human/polyfill_label_B.npy
  p_interval:
  - 0.95
  split: test
  vel: false
  window_size: 64
train_feeder_args:
  bone: true
  data_path: ./data/uav-human/3d/train_joint.npy
  debug: false
  label_path: ./data/uav-human/3d/train_label.npy
  normalization: false
  p_interval:
  - 0.5
  - 1
  random_choose: false
  random_move: false
  random_rot: true
  random_shift: false
  split: train
  vel: false
  window_size: 64
warm_up_epoch: 5
weight_decay: 0.0004
weights: ./checkpoints/epoch_70_17920.pt
work_dir: ./work_dir/ctrgcn_B_test
